Add option to set the working directory for degoss
naftulikay/ansible-role-degoss pull request #51
Opened 2019-10-07 19:48 UTC by bigjazzsound

If SELinux is enabled on the remote host, ansible cannot execute the workdir files in `/tmp`.

I have added an option to set the workdir that degoss puts the files in to mitigate the issue.

2019-10-08 00:00 UTC, naftulikay requested changes
Looks great, can you instead move this variable to `degoss_base_workdir` or `degoss_workdir_base`? I want it to be a little bit clearer that it sets the _base_ directory and generates a temporary directory within that base directory.

Thank you for your contribution! :clap:

2019-10-08 13:01 UTC, bigjazzsound commented
I have updated it to `degoss_base_workdir`. Can you review? Thanks!

2019-10-10 18:23 UTC, naftulikay approved these changes
LGTM :+1:

Thank you for your contribution!

2019-10-10 18:23 UTC, merged

2019-10-10 18:25 UTC, naftulikay commented
Released in [v3.1.0](https://github.com/naftulikay/ansible-role-degoss/releases/tag/v3.1.0).